config/routes.rb
Jcoaching::Application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'registrations'
  }

  devise_scope :user do
    match 'users/success', to: 'registrations#success', via: [:get, :post]
  end
  root "pages#home"

  get 'about' => 'pages#about'
  get 'videos' => 'pages#videos'
  get 'testimonies' => 'pages#testimonials'
  get 'confirmation' => 'pages#confirmation'

  get 'lp/smartvideo1' => 'lp#smartvid1'

  get 'lp/checkout' => 'lp#checkout'
  get 'lp/cancel' => 'lp#cancels'

  get 'lp/reg21agHwcm' => 'devise/registrations#new'

  get 'basics' => 'basics#home'
  get 'basics/stretches' => 'basics#stretches'
  get 'basics/wriststretches' => 'basics#wristStretches'
  get 'basics/foundationprinciples' => 'basics#foundationPrinciples'

  get 'core' => 'core#home'
    get 'core/foundation/toprock' => 'core#f_toprock'
    get 'core/foundation/footwork1' => 'core#f_footwork_1'
    get 'core/foundation/footwork2' => 'core#f_footwork_2'
    get 'core/foundation/freeze1' => 'core#f_freeze_1'
    get 'core/foundation/freeze2' => 'core#f_freeze_2'  

    get 'core/power/swipes' => 'core#p_swipes'
    get 'core/power/flares' => 'core#p_flares'
    get 'core/power/turtles' => 'core#p_turtles'
    get 'core/power/glides' => 'core#p_glides'

    get 'core/bodyrock/abs' => 'core#b_abs'

get 'target' => 'target#home'
  get 'target/music1' => 'target#music_1'
  get 'target/music1' => 'target#music_2'
  get 'target/music1' => 'target#music_3'
  get 'target/music1' => 'target#music_4'
  get 'target/music1' => 'target#music_5'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :presence => { :message => "Please enter your email address" }
  validates :password, :presence => { :message => "Please enter password" }
  validates :password, :confirmation => true, unless: Proc.new { |a| a.password_confirmation.blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController
	
before_filter :authenticate_user!
	def stretches 

	end

	def wristStretches 

	end

	def foundationPrinciples 

	end

end

app/controllers/bonus_controller.rb
class BonusController < ApplicationController
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
end

app/controllers/lp_controller.rb
class LpController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  rescue_from Paypal::Exception::APIError, with: :paypal_api_error

  def create
    @user = User.new user_params

    if @user.valid?
      session[:user] = params[:user]

      request = Paypal::Express::Request.new PAYPAL_CONFIG

      response = request.setup(
        payment_request(50),
        users_success_url,
        cancel_user_registration_url
      )
      redirect_to response.redirect_uri  
    else
      render 'new'
    end
    
  end


  def success

    # To checkout
    request   = Paypal::Express::Request.new PAYPAL_CONFIG
    response = request.checkout!(
      params[:token],
      params[:PayerID],
      payment_request(50)
    )

    params[:user] = session[:user]
    @user = User.new user_params
    
    if @user.save
      sign_up :user, @user
      redirect_to after_sign_up_path_for(@user)
    else
      render 'new'
    end
  end


  def cancel
    render 'new'
  end


  private

  def paypal_api_error(e)
    redirect_to root_url, error: e.response.details.collect(&:long_message).join('<br />')
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def payment_request(amount)
    Paypal::Payment::Request.new(
      :currency_code => :USD,     # if nil, PayPal use USD as default
      :description   => "You have to pay $#{amount} for sign up",    # item description
      :amount        => amount    # item value
    ) 
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    uid = request.env['omniauth.auth'].uid
    user = User.where(uid: uid).first_or_create
    session[:user_id] = user.id
    redirect_to :root
  end

  def show
    @user = User.find_by_id(session[:user_id])
  end
end

app/controllers/target_controller.rb
class TargetController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/bonus_helper.rb
module BonusHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/target_helper.rb
module TargetHelper
end

app/views/basics/_basics_homenav.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Basics</h3>
  </div>
  <div class="panel-body">
<ul class="media-list">
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="..." alt="...">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "Stretches", basics_stretches_path %>
      </h4>
      This is a test description come check it out.
    </div>
  </li>
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="..." alt="...">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "Wrist Stretches", basics_wriststretches_path %>
      </h4>
      This is a test description come check it out.
    </div>
  </li>
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="..." alt="...">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "Foundation Principles", basics_foundationprinciples_path %>
      </h4>
      This is a test description come check it out.
    </div>
  </li>
</ul>
  </div>
</div>

app/views/basics/_basics_navleft.html.erb
<h4>Basics Training</h4>
  	<div class="list-group">


  	<% if current_page?(basics_stretches_path) %>
  	<%= link_to 'Stretches', basics_stretches_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Stretches', basics_stretches_path, {:class=>"list-group-item"} %>
  	<% end %>

  	<% if current_page?(basics_wriststretches_path) %>
  	<%= link_to 'Wrist Stretches', basics_wriststretches_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Wrist Stretches', basics_wriststretches_path, {:class=>"list-group-item"} %>
  	<% end %>

  	<% if current_page?(basics_foundationprinciples_path) %>
  	<%= link_to 'Foundation Princples', basics_foundationprinciples_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Foundation Princples', basics_foundationprinciples_path, {:class=>"list-group-item"} %>
  	<% end %>

	</div>

	<% if current_page?(basics_foundationprinciples_path)%>
		<div class="list-group">
			<h4>Next Section</h4>
			<%= link_to 'Core Training ->', core_path, {:class=>"list-group-item"} %>
		</div>
	<% end %>

		<div class="list-group">
			<%= link_to '<- Back to index', root_path, {:class=>"list-group-item"} %>
		</div>

app/views/basics/_basics_sidenav.html.erb
<h4>Basics Training</h4>
  	<div class="list-group">


  	<% if current_page?(basics_stretches_path) %>
  	<%= link_to 'Stretches', basics_stretches_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Stretches', basics_stretches_path, {:class=>"list-group-item"} %>
  	<% end %>

  	<% if current_page?(basics_wriststretches_path) %>
  	<%= link_to 'Wrist Stretches', basics_wriststretches_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Wrist Stretches', basics_wriststretches_path, {:class=>"list-group-item"} %>
  	<% end %>

  	<% if current_page?(basics_foundationprinciples_path) %>
  	<%= link_to 'Foundation Princples', basics_foundationprinciples_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Foundation Princples', basics_foundationprinciples_path, {:class=>"list-group-item"} %>
  	<% end %>

	</div>

	<% if current_page?(basics_foundationprinciples_path)%>
		<div class="list-group">
			<h4>Next Section</h4>
			<%= link_to 'Core Training ->', core_path, {:class=>"list-group-item"} %>
		</div>
	<% end %>

		<div class="list-group">
			<%= link_to '<- Back to index', root_path, {:class=>"list-group-item"} %>
		</div>

app/views/basics/_basicsnav.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Basics</h3>
  </div>
  <div class="panel-body">
<ul class="media-list">
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="..." alt="...">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "Stretches", basics_stretches_path %>
      </h4>
      This is a test description come check it out.
    </div>
  </li>
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="..." alt="...">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "Wrist Stretches", basics_wriststretches_path %>
      </h4>
      This is a test description come check it out.
    </div>
  </li>
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="..." alt="...">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "Foundation Principles", basics_foundationprinciples_path %>
      </h4>
      This is a test description come check it out.
    </div>
  </li>
</ul>
  </div>
</div>

app/views/basics/home.html.erb
<%= render 'basics/basics_homenav' %>

app/views/basics/wristStretches.html.erb
<div class="row">

  <div class="col-xs-3">
  
  <%= render 'basics/basics_sidenav' %>
  
  </div>

  <div class="col-xs-9">
  	<h3>Wrist Stretches</h3>
	<iframe src="//player.vimeo.com/video/76790137?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" width="853" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>


	  <ul class="pager">
	  	<li class="previous">
	  		<%= link_to '<- Back: Stretches', basics_stretches_path %>
	  	</li>
    	<li class="next">
    		<%= link_to 'Next: Foundation Principles ->', basics_foundationprinciples_path %>
    	</li>
  	</ul>

	</div>
</div>

<br>
<div class="jumbotron">
    <h2>Wrist Stretches</h2>
    <p>Description content instructions go here.</p>
</div>

app/views/core/_corenav.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Core Training</h3>
  </div>

  <div class="panel-body">
    <ul class="media-list">
      <li class="media">
        <a class="pull-left" href="#">
          <img class="media-object" src="..." alt="...">
        </a>
        <div class="media-body">
          <h4 class="media-heading">Foundation Fundamentals</h4>
          This is a test description come check it out.
           <!-- Nested media object -->
                <div class="media">
                  <a class="pull-left" href="#">
                    <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="http://img.photobucket.com/albums/v628/chaosauron/test_zpsfccc7e56.png">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading"><%= link_to "Introduction to Toprocks", core_foundation_toprock_path %></h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    <!-- Nested media object -->
                  </div>

                  <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="http://img.photobucket.com/albums/v628/chaosauron/test_zpsfccc7e56.png">
                    </a>
                    <div class="media-body">
                    <h4 class="media-heading"><%= link_to "Footwork Foundation 1: The Six Step & Cross-Overs", core_foundation_footwork1_path %></h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>

                  <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="http://img.photobucket.com/albums/v628/chaosauron/test_zpsfccc7e56.png">
                    </a>
                    <div class="media-body">
                    <h4 class="media-heading"><%= link_to "Footwork Foundation 2: The Three Step, Zulu Spins, Sweep", core_foundation_footwork2_path %></h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>

          <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="data:image/png;base64,">
                    </a>
                    <div class="media-body">
                    <h4 class="media-heading"><%= link_to "Fundamental Freezes 1: Plank, Baby, Crossleg", core_foundation_freeze1_path %> </h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>

                  <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="data:image/png;base64,">
                    </a>
                    <div class="media-body">
                    <h4 class="media-heading"><%= link_to "Fundamental Freezes 2: Chair ", core_foundation_freeze2_path %></h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>

                </div>
                <!-- Nested media object -->
        </div>
      </li>
    </ul>


    <ul class="media-list">
      <li class="media">
        <a class="pull-left" href="#">
          <img class="media-object" src="..." alt="...">
        </a>
        <div class="media-body">
          <h4 class="media-heading">Power Moves Now</h4>
          This is a test description come check it out.
           <!-- Nested media object -->
                  <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="data:image/png;base64,">
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading"> <%= link_to "Swipes", core_power_swipes_path %> </h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>

                  <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="data:image/png;base64,">
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading"> <%= link_to "Flares", core_power_flares_path %> </h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>


                <div class="media">
                  <a class="pull-left" href="#">
                    <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="data:image/png;base64,">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading"> <%= link_to "The Turtle", core_power_turtles_path %></h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    <!-- Nested media object -->
                  </div>

                  <div class="media">
                    <a class="pull-left" href="#">
                      <img class="media-object" data-src="holder.js/64x64" alt="Generic placeholder image" src="data:image/png;base64,">
                    </a>
                    <div class="media-body">
                    <h4 class="media-heading"> <%= link_to "Hand Glides & Crickets", core_power_glides_path %></h4>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                    </div>
                  </div>



                </div>
                <!-- Nested media object -->
        </div>
      </li>
    </ul>

<ul class="media-list">
      <li class="media">
        <a class="pull-left" href="#">
          <img class="media-object" src="..." alt="...">
        </a>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to "Body Rock Abs", core_bodyrock_abs_path %></h4>
          This is a test description come check it out.
        </div>
      </li>
    </ul>


  </div>
</div>

app/views/core/_foundation_navleft.html.erb
<h4>Core Foundations</h4>
  	<div class="list-group">


  	<% if current_page?(core_foundation_toprock_path) %>
  	<%= link_to 'Toprocks', core_foundation_toprock_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Toprocks', core_foundation_toprock_path, {:class=>"list-group-item"} %>
  	<% end %>

  	<% if current_page?(core_foundation_footwork1_path) %>
  	<%= link_to 'Footwork Part: 1', core_foundation_footwork1_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Footwork Part: 1', core_foundation_footwork1_path, {:class=>"list-group-item"} %>
  	<% end %>

  	<% if current_page?(core_foundation_footwork2_path) %>
  	<%= link_to 'Footwork Part: 2', core_foundation_footwork2_path, {:class=>"list-group-item active"} %>
  	<% else %>
  	<%= link_to 'Footwork Part: 2', core_foundation_footwork2_path, {:class=>"list-group-item"} %>
  	<% end %>

      <% if current_page?(core_foundation_freeze1_path) %>
    <%= link_to 'Freezes Part: 1', core_foundation_freeze1_path, {:class=>"list-group-item active"} %>
    <% else %>
    <%= link_to 'Freezes Part: 1', core_foundation_freeze1_path, {:class=>"list-group-item"} %>
    <% end %>

    <% if current_page?(core_foundation_freeze2_path) %>
    <%= link_to 'Freezes: Chair', core_foundation_freeze2_path, {:class=>"list-group-item active"} %>
    <% else %>
    <%= link_to 'Freezes: Chair', core_foundation_freeze2_path, {:class=>"list-group-item"} %>
    <% end %>
	</div>

<h5>Other Core Sections</h5>
    <div class="list-group">

    <%= link_to 'Power Moves Now', core_power_swipes_path, {:class=>"list-group-item"} %>

    <%= link_to 'Bodyrock Abs', core_bodyrock_abs_path, {:class=>"list-group-item"} %>
  </div>

	<% if current_page?(basics_foundationprinciples_path)%>
		<div class="list-group">
			<h4>Next Section</h4>
			<%= link_to 'Core Training ->', core_path, {:class=>"list-group-item"} %>
		</div>
	<% end %>

		<div class="list-group">
			<%= link_to '<- Back to index', root_path, {:class=>"list-group-item"} %>
		</div>

app/views/core/_power_navleft.html.erb
<h4>Core Foundations</h4>
<div class="list-group">


  <% if current_page?(core_power_swipes_path) %>
      <%= link_to 'Swipes', core_power_swipes_path, {:class=>"list-group-item active"} %>
  <% else %>
      <%= link_to 'Swipes', core_power_swipes_path, {:class=>"list-group-item"} %>
  <% end %>

  <% if current_page?(core_power_flares_path) %>
      <%= link_to 'Flares', core_power_flares_path, {:class=>"list-group-item active"} %>
  <% else %>
      <%= link_to 'Flares', core_power_flares_path, {:class=>"list-group-item"} %>
  <% end %>

  <% if current_page?(core_power_turtles_path) %>
      <%= link_to 'Turtles', core_power_turtles_path, {:class=>"list-group-item active"} %>
  <% else %>
      <%= link_to 'Turtles', core_power_turtles_path, {:class=>"list-group-item"} %>
  <% end %>

  <% if current_page?(core_power_glides_path) %>
      <%= link_to 'Hand Glides & Crickets', core_power_glides_path, {:class=>"list-group-item active"} %>
  <% else %>
      <%= link_to 'Hand Glides & Crickets', core_power_glides_path, {:class=>"list-group-item"} %>
  <% end %>
</div>

<h5>Other Core Sections</h5>
<div class="list-group">

  <%= link_to 'Foundation Fundamentals', core_foundation_toprock_path, {:class=>"list-group-item"} %>

  <%= link_to 'Bodyrock Abs', core_bodyrock_abs_path, {:class=>"list-group-item"} %>
</div>

<% if current_page?(basics_foundationprinciples_path)%>
    <div class="list-group">
      <h4>Next Section</h4>
      <%= link_to 'Core Training ->', core_path, {:class=>"list-group-item"} %>
    </div>
<% end %>

<div class="list-group">
  <%= link_to '<- Back to index', root_path, {:class=>"list-group-item"} %>
</div>

app/views/core/b_abs.html.erb
<div class="row">

  <div class="col-xs-3">

    <h5>Other Core Sections</h5>
    <div class="list-group">

      <%= link_to 'Foundation Fundamentals', core_foundation_toprock_path, {:class=>"list-group-item"} %>

      <%= link_to 'Bodyrock Abs', basics_wriststretches_path, {:class=>"list-group-item"} %>
    </div>


        <div class="list-group">
          <h4>Next Section</h4>
          <%= link_to 'Target Training ->', core_path, {:class=>"list-group-item"} %>
        </div>


  </div>

  <div class="col-xs-9">
    <h3>Bodyrock Abs</h3>
  <iframe src="//player.vimeo.com/video/76790135?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" width="853" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

    <ul class="pager">
      <li class="previous">
        <%= link_to '<- Back: Power Moves', core_power_swipes_path %>
      </li>
      <li class="next">
        <%= link_to 'Next Section: Target Training ->', core_foundation_footwork2_path %>
      </li>
  </ul>

  </div>
</div>

<br>
<div class="jumbotron">
    <h2>Foundation Fundamentals: Footwork Foundation 1</h2>
    <p>Description content instructions go here.</p>
</div>

app/views/core/p_flares.html.erb
<div class="row">

  <div class="col-xs-3">
  
  <%= render 'core/power_navleft' %>
  
  </div>

  <div class="col-xs-9">
    <h3>Power Moves: Flares</h3>
  <iframe src="//player.vimeo.com/video/76790295?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" width="853" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

    <ul class="pager">
      <li class="previous">
        <%= link_to '<- Back: Swipes', core_power_swipes_path %>
      </li>
      <li class="next">
        <%= link_to 'Next Section: The Turtle ->', core_power_turtles_path %>
      </li>
  </ul>

  </div>
</div>

<br>
<div class="jumbotron">
    <h2>Foundation Fundamentals: Footwork Foundation 1</h2>
    <p>Description content instructions go here.</p>
</div>

app/views/core/p_glides.html.erb
<div class="row">

  <div class="col-xs-3">
  
  <%= render 'core/power_navleft' %>
  
  </div>

  <div class="col-xs-9">
    <h3>Power Moves: Hand Glides & Crickets</h3>
  <iframe src="//player.vimeo.com/video/76790277?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" width="853" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

    <ul class="pager">
      <li class="previous">
        <%= link_to '<- Back: The Turtle', core_power_turtles_path %>
      </li>
      <li class="next">
        <%= link_to 'Next Section: Body Rock Abs->', core_bodyrock_abs_path %>
      </li>
  </ul>

  </div>
</div>

<br>
<div class="jumbotron">
    <h2>Foundation Fundamentals: Footwork Foundation 1</h2>
    <p>Description content instructions go here.</p>
</div>

app/views/layouts/_header.html.erb
<center>

  <div class="visible-md visible-lg fillnavwidth">
  <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/jskeegraphics/logo.png", :class => "img-responsive"), root_path %>
  </div>

    <div class="visible-xs visible-sm fillnavwidth">
  <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/jskeegraphics/mobilelogo.png", :class => "img-responsive"), root_path %>
  </div>

</center>

<nav class="navbar navbar-default navcolor fillnavwidth" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
    <ul class="nav navbar-nav navfontsize">

    <% if user_signed_in? %>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Basics", basics_path %></li>
      <li><%= link_to "Core", core_path %></li>
      <li><%= link_to "Target", videos_path %></li>
      <li><%= link_to "Bonus", videos_path %></li>
      <li><%= link_to "Coaching", videos_path %></li>
    <% else %>


    <% end %>
    </ul>
    
    <ul class="nav navbar-nav navbar-right navfontsize">
 <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
          
            <li><%= link_to "Members Login", new_user_session_path %></li>
          

      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->

</nav>